# Generated by Django 5.2.4 on 2025-07-08 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_year', models.IntegerField()),
                ('experience_level', models.CharField(max_length=2)),
                ('job_title', models.CharField(max_length=255)),
                ('salary', models.IntegerField()),
                ('salary_currency', models.CharField(max_length=10)),
                ('salary_in_usd', models.IntegerField()),
                ('employee_residence', models.CharField(max_length=100)),
                ('remote_ratio', models.IntegerField()),
                ('company_location', models.CharField(max_length=100)),
                ('company_size', models.CharField(max_length=2)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.candidate')),
                ('employment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.contract')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.industry')),
                ('skill', models.ManyToManyField(blank=True, to='jobs.skill')),
            ],
        ),
    ]
